#!/bin/bash

sudo docker build --build-arg FNS_BRANCH=develop --build-arg RAS_BRANCH=develop --build-arg AS_BRANCH=develop \
 --build-arg COMMON_BRANCH=develop --no-cache -t fogbow/federated-network-service:develop .

