#!/bin/bash

./push fogbow/federated-network-service:latest

sudo docker tag fogbow/federated-network-service:latest fogbow/federated-network-service:buzios
./push fogbow/federated-network-service:buzios

